steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'gcr.io/$PROJECT_ID/portfolio:latest',
      '--build-arg',
      'MIXPANEL_TOKEN=$_MIXPANEL_TOKEN',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/portfolio:latest'
    ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      'portfolio',
      '--image',
      'gcr.io/$PROJECT_ID/portfolio:latest',
      '--region',
      'us-central1',
      '--platform',
      'managed',
      '--port',
      '3000',
      '--allow-unauthenticated'
    ]